### ISSUE TITLE
Have the accumulated times ignore B/L

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/slack-bots#2]
B/L is time that the person will be away but won't be considered as time off. We have people report it so that we're aware beforehand that they will be absent. So I think it makes sense to ignore B/L completely in matters of accumulated time reports.

**Comment by BTT21000** [comment]
B/L is now ignored in matters of accumulated time reports. 
And the related latest code available in the latest [commit](https://github.com/api3dao/slack-bots/commit/3990e1716f1196a60ca24242c88a188e577636a1) of https://github.com/api3dao/slack-bots/tree/main/technical-time-off
